app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

home:
    path: /home
    defaults:
        _controller: AppBundle:Main:home
